app = "interpretive-seeder"
primary_region = "ams"

image = "ghcr.io/gowthamsundaresan/interpretive-markets-backend-seeder:latest"

[env]
NETWORK = "sepolia"
START_BLOCK = "10963000"

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1
